"""test

Revision ID: 11046cd022d6
Revises: a81ec513c2c5
Create Date: 2023-10-01 12:03:26.912511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11046cd022d6'
down_revision = 'a81ec513c2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_items')
    op.drop_table('carts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('creation_date', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('last_updated_at', sa.DATETIME(), nullable=True),
    sa.Column('test_column', sa.INTEGER(), nullable=True),
    sa.CheckConstraint("status IN ('OPEN', 'CHECKOUT', 'CLOSED', 'REMOVED')", name='cartstatus'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cart_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
