"""remove test

Revision ID: 13d7b76de335
Revises: 428cf2735563
Create Date: 2023-10-01 12:10:35.495003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d7b76de335'
down_revision = '428cf2735563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'test_column')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('test_column', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
