"""test

Revision ID: 7237f3b14847
Revises: 11046cd022d6
Create Date: 2023-10-01 12:04:00.712032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7237f3b14847'
down_revision = '11046cd022d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
