"""add last udated at in cart

Revision ID: 762724515739
Revises: ed3baad7c02b
Create Date: 2023-10-01 11:42:09.809680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762724515739'
down_revision = 'ed3baad7c02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carts')
    op.drop_table('cart_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cart_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('creation_date', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'CHECKOUT', 'CLOSED', 'REMOVED')", name='cartstatus'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
