"""test

Revision ID: 84ef75e38456
Revises: b1627cffd0f3
Create Date: 2023-10-01 11:56:54.534666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ef75e38456'
down_revision = 'b1627cffd0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
