"""test

Revision ID: b1627cffd0f3
Revises: e998b6b84b14
Create Date: 2023-10-01 11:55:04.080589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1627cffd0f3'
down_revision = 'e998b6b84b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
